// =============================================================================
// MOCK DATA — UI-only fixtures used until API routes are wired to Prisma.
// Field names here are tuned to the current pages, NOT the Prisma schema.
// Once the data layer lands, replace these imports with React Server Component
// queries via `prisma` (see /lib/prisma.ts) and align field names with the
// `Lead`, `Product`, `Supplier` models.
// =============================================================================

export const mockProducts = [
  {
    id: "PRD-001",
    name: "Surgical Drape Kit - General Surgery",
    category: "Surgical Drapes & Procedure Kits",
    sku: "UH-SDK-GS-001",
    costPrice: 180,
    sellingPrice: 320,
    exportPrice: 8.5,
    moq: 500,
    unit: "kit",
    supplier: "Gujarat MedPack Pvt Ltd",
    leadTime: "7-10 days",
    certifications: ["ISO 13485", "CE Mark"],
    exportAvailable: true,
    stock: 2500,
    image: "/products/surgical-drape.jpg",
  },
  {
    id: "PRD-002",
    name: "IV Infusion Set - Standard",
    category: "IV Infusion Sets",
    sku: "UH-IVS-STD-001",
    costPrice: 8,
    sellingPrice: 14,
    exportPrice: 0.42,
    moq: 5000,
    unit: "piece",
    supplier: "Romsons Group",
    leadTime: "5-7 days",
    certifications: ["ISO 13485", "CE Mark", "WHO GMP"],
    exportAvailable: true,
    stock: 50000,
    image: "/products/iv-set.jpg",
  },
  {
    id: "PRD-003",
    name: "Surgical Sutures - Polyglactin 910",
    category: "Surgical Sutures",
    sku: "UH-SUT-PG910-001",
    costPrice: 45,
    sellingPrice: 78,
    exportPrice: 1.8,
    moq: 1000,
    unit: "piece",
    supplier: "Sutures India Pvt Ltd",
    leadTime: "10-14 days",
    certifications: ["ISO 13485", "CE Mark", "WHO GMP"],
    exportAvailable: true,
    stock: 15000,
    image: "/products/sutures.jpg",
  },
  {
    id: "PRD-004",
    name: "IV Cannula - 20G",
    category: "IV Catheters / Cannulas",
    sku: "UH-IVC-20G-001",
    costPrice: 12,
    sellingPrice: 22,
    exportPrice: 0.55,
    moq: 5000,
    unit: "piece",
    supplier: "Poly Medicure Ltd",
    leadTime: "7-10 days",
    certifications: ["ISO 13485", "CE Mark", "CDSCO Registered"],
    exportAvailable: true,
    stock: 80000,
    image: "/products/cannula.jpg",
  },
  {
    id: "PRD-005",
    name: "Anesthesia Breathing Circuit",
    category: "Anesthesia Accessories",
    sku: "UH-ANS-BC-001",
    costPrice: 250,
    sellingPrice: 450,
    exportPrice: 12.0,
    moq: 200,
    unit: "piece",
    supplier: "Gujarat MedPack Pvt Ltd",
    leadTime: "10-14 days",
    certifications: ["ISO 13485", "CE Mark"],
    exportAvailable: true,
    stock: 3000,
    image: "/products/breathing-circuit.jpg",
  },
  {
    id: "PRD-006",
    name: "Nitrile Examination Gloves - Medium",
    category: "Disposable Gloves",
    sku: "UH-GLV-NIT-M-001",
    costPrice: 3.5,
    sellingPrice: 6,
    exportPrice: 0.12,
    moq: 50000,
    unit: "piece",
    supplier: "Kanam Latex Industries",
    leadTime: "5-7 days",
    certifications: ["ISO 13485", "CE Mark", "FDA 510(k)"],
    exportAvailable: true,
    stock: 500000,
    image: "/products/gloves.jpg",
  },
];

export const mockSuppliers = [
  {
    id: "SUP-001",
    name: "Gujarat MedPack Pvt Ltd",
    location: "Ahmedabad, Gujarat",
    contact: "+91 79 XXXX XXXX",
    email: "sales@gujaratmedpack.com",
    certifications: ["ISO 13485", "CE Mark", "WHO GMP"],
    products: ["Surgical Drapes", "Anesthesia Accessories", "PPE Kits"],
    reliabilityScore: 92,
    trustScore: 88,
    totalOrders: 45,
    onTimeDelivery: 94,
    qualityRejectionRate: 1.2,
  },
  {
    id: "SUP-002",
    name: "Sutures India Pvt Ltd",
    location: "Bangalore, Karnataka",
    contact: "+91 80 XXXX XXXX",
    email: "export@suturesindia.com",
    certifications: ["ISO 13485", "CE Mark", "WHO GMP", "CDSCO Registered"],
    products: ["Surgical Sutures", "Surgical Staples"],
    reliabilityScore: 96,
    trustScore: 94,
    totalOrders: 28,
    onTimeDelivery: 97,
    qualityRejectionRate: 0.5,
  },
  {
    id: "SUP-003",
    name: "Romsons Group",
    location: "Agra, Uttar Pradesh",
    contact: "+91 562 XXXX XXXX",
    email: "exports@romsons.com",
    certifications: ["ISO 13485", "CE Mark", "FDA 510(k)"],
    products: ["IV Sets", "Urology Catheters", "Blood Bags", "Wound Care"],
    reliabilityScore: 89,
    trustScore: 85,
    totalOrders: 62,
    onTimeDelivery: 88,
    qualityRejectionRate: 2.1,
  },
  {
    id: "SUP-004",
    name: "Poly Medicure Ltd",
    location: "Faridabad, Haryana",
    contact: "+91 129 XXXX XXXX",
    email: "info@polymedicure.com",
    certifications: ["ISO 13485", "CE Mark", "WHO GMP", "CDSCO Registered"],
    products: ["IV Cannulas", "Blood Management", "Dialysis Products"],
    reliabilityScore: 95,
    trustScore: 93,
    totalOrders: 35,
    onTimeDelivery: 96,
    qualityRejectionRate: 0.8,
  },
];

export const mockLeads = [
  {
    id: "CRM-001",
    name: "City Hospital Jaipur",
    type: "Hospital",
    contact: "Dr. Rajesh Sharma",
    email: "procurement@cityhospital.in",
    phone: "+91 98XXX XXXXX",
    stage: "Quotation Sent",
    value: 450000,
    products: ["IV Sets", "Surgical Drapes", "Gloves"],
    lastContact: "2025-05-08",
    nextFollowUp: "2025-05-15",
  },
  {
    id: "CRM-002",
    name: "KEMSA - Kenya",
    type: "Government",
    contact: "James Ochieng",
    email: "procurement@kemsa.go.ke",
    phone: "+254 XXX XXXXXX",
    stage: "RFQ Received",
    value: 2500000,
    products: ["Surgical Kits", "IV Sets", "Sutures"],
    lastContact: "2025-05-10",
    nextFollowUp: "2025-05-12",
  },
  {
    id: "CRM-003",
    name: "Al Noor Hospital Group",
    type: "Hospital Chain",
    contact: "Ahmed Al-Rashid",
    email: "supply@alnoor.ae",
    phone: "+971 XX XXX XXXX",
    stage: "Negotiation",
    value: 1800000,
    products: ["Anesthesia Accessories", "IV Cannulas", "Surgical Sutures"],
    lastContact: "2025-05-09",
    nextFollowUp: "2025-05-13",
  },
  {
    id: "CRM-004",
    name: "Apex Multispeciality Hospital",
    type: "Hospital",
    contact: "Priya Mehta",
    email: "purchase@apexhospital.in",
    phone: "+91 97XXX XXXXX",
    stage: "Lead",
    value: 280000,
    products: ["IV Sets", "Gloves", "Wound Care"],
    lastContact: "2025-05-11",
    nextFollowUp: "2025-05-14",
  },
];

export const mockAnalytics = {
  totalRevenue: 4850000,
  monthlyGrowth: 23.5,
  activeQuotations: 18,
  conversionRate: 34.2,
  totalProducts: 156,
  activeSuppliers: 12,
  exportOrders: 4,
  pendingRFQs: 7,
  revenueByMonth: [
    { month: "Jan", revenue: 320000, orders: 8 },
    { month: "Feb", revenue: 450000, orders: 12 },
    { month: "Mar", revenue: 580000, orders: 15 },
    { month: "Apr", revenue: 720000, orders: 18 },
    { month: "May", revenue: 890000, orders: 22 },
  ],
  topProducts: [
    { name: "IV Infusion Sets", revenue: 1200000, units: 85000 },
    { name: "Surgical Drape Kits", revenue: 960000, units: 3000 },
    { name: "IV Cannulas", revenue: 880000, units: 40000 },
    { name: "Surgical Sutures", revenue: 780000, units: 10000 },
    { name: "Anesthesia Circuits", revenue: 675000, units: 1500 },
  ],
  exportByRegion: [
    { region: "East Africa", value: 1200000, orders: 3 },
    { region: "GCC", value: 1800000, orders: 2 },
    { region: "SAARC", value: 450000, orders: 2 },
  ],
};
